---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: freebsd-9.3
  - name: freebsd-10.1
  - name: opensuse-13.1
  - name: debian-7.8
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-5.11
  - name: centos-6.6
  - name: centos-7.0
  - name: fedora-21

suites:
  - name: package
    run_list:
      - recipe[my-lb]
    attributes:
      haproxy:
        install_method: package
  - name: source
    run_list:
      - recipe[my-lb]
    attributes:
      haproxy:
        install_method: source
  - name: ppa
    run_list:
      - recipe[my-lb]
    attributes:
      haproxy:
        install_method: ppa
    excludes:
      - freebsd-9.3
      - freebsd-10.1
      - opensuse-13.1
      - debian-7.8
      - centos-5.11
      - centos-6.6
      - centos-7.0
      - fedora-21
